### ISSUE TITLE
Stage : Roadmap 🔥 

### ISSUE THREAD

**Issue by CinquinAndy** [CinquinAndy/formenu-front#23]
_Listing des idées que l'on pourrait aborder dans le cadre de la formation de quelqu'un (spoiler alert : trauma obligatoire)_

# Roadmap principale
- [ ] Bases de développement web : HTML, CSS, JavaScript
- [ ] Bases de développement sur différents paradigmes : Objet / Fonctionnel
- [ ] Utilisation de base de données : SQL, conception de bases de données relationnelles (UML), ORM (Object-Relational Mapping)
- [ ] Workflow de travail : utilisation de Git, méthodes de travail collaboratives (CI/CD, Agile, Scrum, Kanban)
- [ ] Bases de la sécurité : OWASP, sécurité des sites web, gestion des accès et des identités, JWT, les attaques basiques (xss / injections etc), cryptographie, gestion des certificats SSL
- [ ] Bases de réseau : TCP/IP, DNS, VPS, Adressage
- [ ] Bases de Linux : commandes shell, système de fichiers, gestion des processus, automatisation 
- [ ] PaaS : CapRover 
- [ ] Front-end : accessibilité, charte graphique, frameworks CSS (TailwindCSS), frameworks JavaScript (React), Framework React (NextJS)
- [ ] Développement de compétences en UX/UI : wireframes, prototypage, test utilisateur
- [ ] Utilisation des outils modernes : méthodes agiles, outils de design (Figma), gestion de projet (Trello), partages de bonnes pratiques et outils de développement (Prettier, ESLint)
- [ ] Back-end : utilisation de frameworks (Strapi, Pocket Base), conception d'API RESTful, (point sur GraphQL à ajouter)
- [ ] Tests automatisés : Cypress, Percy, Jest
- [ ] Optimisation web : Lighthouse, W3C, Wave, IBM accessibility tool
- [ ] Intégration de nouvelles technologies et de nouvelles pratiques : Docker, TailwindCSS, NextJS, etc.
- [ ] Partie complète sur les enjeux SEO / SEA / Communications 
- [ ] Partie complète sur l'utilisation des IA dans notre quotidiens ( GPT / Copilot ) 
- [ ] Process de création d'un SaaS 
- [ ] Awesome-software-architecture

# Général
- [ ] Veille technologique : mise en place d'une veille efficace pour rester à jour sur les nouvelles technologies et les bonnes pratiques
- [ ] Utilisation des outils au quotidien : Syncthings, Obsidian, Git Kraken
- [ ] Apprentissage du second cerveau : début de ses études, prise de notes efficace, gestion de l'information

# Optionnel 
- [ ] Développement mobile : Flutter / React Native 
- [ ] Intégration de systèmes de paiement tiers (Stripe, PayPal)
- [ ] Point sur les BDD NoSQL 
- [ ] Utilisation de la méthode DevOps : automatisation des processus de déploiement, monitoring des applications en production, gestion des logs, etc. ( Point sur betteruptime // monitoring de façon général ) 
- [ ] Utilisation de plateformes de déploiement (ex: Heroku, AWS, GCP, Azure)
- [ ] Utilisation d'un CMS (ex: WordPress) et développement de thèmes et plugins personnalisés ( Techniques avec ACF plugin ) 
- [ ] Point législatif : RGPD etc
- [ ] Conception de solutions de scaling horizontal et vertical pour les applications web
